version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sabir123QW!&
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports: 
      - "8000:8000"
    volumes:
      - ./:/usr/src/app #:ro read only
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=sabir123QW!&
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e8
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXP_MIN=30

volumes:
  postgres_db:
